name = "Polyurethanes"
uuid = "770902dd-bf43-47cf-89f4-4676401ab19a"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br> and contributors"]
version = "0.1.0"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Catalyst = "7"
DifferentialEquations = "6"
Parameters = "0.12"
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
